### ISSUE TITLE
`concurrent-queue` is unavailable for `android` target

### ISSUE THREAD

**Issue by jvjfk** [smol-rs/async-signal#16]
`concurrent-queue` is imported (in Cargo.toml) only if target is `linux`, but is used when target is `linux` OR `android`.

So, async-signal last release (v0.2.1) does not build on `android` target.

Thank you !

>Cargo.toml
```toml
[target.'cfg(target_os = "linux")'.dependencies]
concurrent-queue = "2.2.0"
```

>lib.rs
```rust
} else if #[cfg(any(target_os = "android", target_os = "linux"))] {
    mod signalfd;
    use signalfd as sys;
}
```

>signalfd.rs
```rust
use concurrent_queue::ConcurrentQueue;
```
